export const Rules = () => {
    return (
        <main className="main__content rules">
            <h2 className="main__title rules__title">Regulamin</h2>
            <div className="rules__section main__subsection">
                <p className="rules__item">1. Nie robić syfu, chyba że o to poproszę!</p>
                <p className="rules__item">2. W sumie to tyle, bo mi się nie chcę pisać, a poza tym i tak nikt by tego nie przeczytał więc kekw.</p>
                <p className="rules__item">3. A dalej to już wiadomo, nasz kochany "Lorem Ipsum".</p>
                <p className="rules__item">4. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
                <p className="rules__item">5. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
                <p className="rules__item">6. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
                <p className="rules__item">7. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
                <p className="rules__item">8. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
                <p className="rules__item">9. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
                <p className="rules__item">10. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
                <p className="rules__item">11. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
                <p className="rules__item">12. Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident modi, quis, nihil, possimus in sint iusto nulla repellendus praesentium adipisci cumque est vel eum quaerat illo ipsam dignissimos quasi dolore?</p>
            </div>
        </main>
    );
};